name: client_data_firebase
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ^3.24.0

dependencies:
  cloud_firestore: ^6.1.0
  data_layer: ^0.0.1-beta.7
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  equatable: ^2.0.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
